### PR TITLE
Fix for #29: Added jaxws-api dependency

### PR DESCRIPTION
**Pull request by MatthiasLohr**

### CODE REVIEW

**Comment by MatthiasLohr** [comment]
@gdenning, can you take a look? Thanks!

**Comment by gdenning** [comment]
Thanks Matthias!!

**Comment by MatthiasLohr** [comment]
Can you create a new bugfix release for that please? Thanks!

**Comment by gdenning** [comment]
Done!  Version 1.0.9 released.

**Comment by MatthiasLohr** [comment]
Thank you very much!

**Pull request merged**
